'use strict';
/**
 * Vertical promo for TikTok / Reels / Shorts — 1080×1920, 30 fps.
 *
 * The property photographs carry the film; the opening and closing plates are
 * generated by the same procedural dusk scene as the site hero, so the cuts
 * that photography can't cover are filled with matching material rather than
 * stock. Ken Burns moves, beat-timed cuts, brand typography, film grade.
 *
 * Deliberately silent: TikTok creators attach trending audio in-app, and the
 * edit is cut to a 120 bpm grid so it lands on the beat of whatever they pick.
 */
const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');
const ffmpeg = require('ffmpeg-static');
const { createCanvas, loadImage, GlobalFonts } = require('@napi-rs/canvas');
const scene = require('./scene');

GlobalFonts.registerFromPath(path.join(__dirname, 'Fraunces.ttf'), 'Fraunces');
GlobalFonts.registerFromPath(path.join(__dirname, 'InstrumentSans.ttf'), 'InstrumentSans');

const W = 1080, H = 1920, FPS = 30;
const IMG = path.join(__dirname, '..', 'site', 'assets', 'img');
const OUT = path.join(__dirname, '..', 'site', 'assets');

const GOLD = '#e2b26a';
const CREAM = '#f4efe6';

/* ── timing ────────────────────────────────────────────────────────
   120 bpm → a beat is 15 frames. Every cut sits on a beat boundary. */
const B = 15;
const sec = (n) => Math.round(n * FPS);

/**
 * Shots. `z` is the Ken Burns zoom [from, to]; `p` the pan in fractions of
 * the overscan, [fromX, fromY, toX, toY]. `t` is an optional caption.
 */
const SHOTS = [
  { kind: 'plate', d: B * 5, t: null },                                  // 2.5s opener
  { img: 'p00', d: B * 4, z: [1.06, 1.18], p: [0, .1, .04, -.02], t: ['ÉCRIN', 'MIROIR'] },
  { img: 'p01', d: B * 4, z: [1.20, 1.06], p: [-.06, 0, .05, .02] },
  { img: 'p02', d: B * 4, z: [1.18, 1.05], p: [.04, .05, -.03, -.04] },
  { img: 'p10', d: B * 4, z: [1.05, 1.20], p: [0, -.05, .02, .06], t: ['BALNÉO'] },
  { img: 'p11', d: B * 3, z: [1.18, 1.06], p: [.05, .02, -.04, -.03] },
  // The projector, not the screen: the listing's screen shot is filled with a
  // third party's programme, which is heavier in an advert than in a thumbnail.
  { src: '20-fc2aae71-4e46-4839-9069-57bcf2681027.jpeg',
    d: B * 4, z: [1.04, 1.18], p: [-.03, 0, .04, .01], t: ['CINÉMA', 'PRIVÉ'] },
  { img: 'p07', d: B * 4, z: [1.16, 1.04], p: [.04, -.04, -.04, .04] },
  { img: 'p09', d: B * 3, z: [1.05, 1.17], p: [0, .04, .03, -.03] },
  { img: 'p04', d: B * 3, z: [1.17, 1.05], p: [-.04, 0, .04, .02] },
  // rapid montage — one beat each
  { img: 'p13', d: B * 2, z: [1.10, 1.20], p: [0, 0, .03, .03], cut: 'hard' },
  { img: 'p14', d: B * 2, z: [1.20, 1.10], p: [.03, 0, -.03, .02], cut: 'hard' },
  { img: 'p05', d: B * 2, z: [1.08, 1.18], p: [-.03, .02, .03, -.02], cut: 'hard' },
  { img: 'p03', d: B * 2, z: [1.18, 1.08], p: [.02, -.02, -.02, .03], cut: 'hard' },
  { kind: 'end', d: B * 7 },                                             // 3.5s end card
];

const XF = 6;              // crossfade frames between shots
const TOTAL = SHOTS.reduce((n, s) => n + s.d, 0);

/* ── helpers ───────────────────────────────────────────────────────── */
const clamp = (v, a, b) => (v < a ? a : v > b ? b : v);
const smooth = (t) => t * t * (3 - 2 * t);
const lerp = (a, b, t) => a + (b - a) * t;

/** Cover-fit an image, then zoom and pan within the overscan. */
function drawCover(ctx, img, zoom, panX, panY) {
  const base = Math.max(W / img.width, H / img.height);
  const s = base * zoom;
  const w = img.width * s, h = img.height * s;
  const x = (W - w) / 2 + panX * (w - W) * 0.5;
  const y = (H - h) / 2 + panY * (h - H) * 0.5;
  ctx.drawImage(img, x, y, w, h);
}

/** Caption: brand-spaced uppercase, rising in and out. */
function drawCaption(ctx, lines, prog, dur) {
  const inT = clamp(prog * dur / 12, 0, 1);
  const outT = clamp((dur - prog * dur) / 10, 0, 1);
  const a = smooth(inT) * smooth(outT);
  if (a <= 0.01) return;

  const size = 78;
  const lh = size * 1.18;
  const y0 = H * 0.5 - ((lines.length - 1) * lh) / 2;
  const rise = (1 - smooth(inT)) * 26;

  ctx.save();
  ctx.textAlign = 'center';
  ctx.font = `500 ${size}px Fraunces`;
  ctx.letterSpacing = '10px';

  lines.forEach((ln, i) => {
    const y = y0 + i * lh + rise;
    ctx.globalAlpha = a * 0.55;
    ctx.fillStyle = 'rgba(0,0,0,0.9)';
    ctx.filter = 'blur(18px)';
    ctx.fillText(ln, W / 2, y + 4);
    ctx.filter = 'none';
    ctx.globalAlpha = a;
    ctx.fillStyle = CREAM;
    ctx.fillText(ln, W / 2, y);
  });

  // hairline rule under the block, drawing outward
  const ruleW = 150 * smooth(inT);
  ctx.globalAlpha = a * 0.85;
  ctx.fillStyle = GOLD;
  ctx.fillRect(W / 2 - ruleW / 2, y0 + (lines.length - 1) * lh + 42 + rise, ruleW, 2);
  ctx.restore();
}

/* ── the film grade, shared by every frame ─────────────────────────── */
function buildGrain() {
  const tiles = [];
  let seed = 7;
  const rnd = () => (seed = (seed * 1103515245 + 12345) & 0x7fffffff) / 0x7fffffff;
  for (let t = 0; t < 5; t++) {
    const g = createCanvas(384, 384);
    const gx = g.getContext('2d');
    const im = gx.createImageData(384, 384);
    for (let i = 0; i < 384 * 384; i++) {
      const v = 128 + (rnd() - 0.5) * 240;
      const o = i * 4;
      im.data[o] = im.data[o + 1] = im.data[o + 2] = clamp(v, 0, 255);
      im.data[o + 3] = 255;
    }
    gx.putImageData(im, 0, 0);
    tiles.push(g);
  }
  return tiles;
}

function grade(ctx, f, grain) {
  // warm highlight lift
  ctx.globalCompositeOperation = 'lighter';
  const warm = ctx.createRadialGradient(W * 0.5, H * 0.42, 0, W * 0.5, H * 0.42, H * 0.6);
  warm.addColorStop(0, 'rgba(226,178,106,0.055)');
  warm.addColorStop(1, 'rgba(0,0,0,0)');
  ctx.fillStyle = warm;
  ctx.fillRect(0, 0, W, H);
  ctx.globalCompositeOperation = 'source-over';

  // vignette
  const vg = ctx.createRadialGradient(W / 2, H / 2, H * 0.28, W / 2, H / 2, H * 0.72);
  vg.addColorStop(0, 'rgba(0,0,0,0)');
  vg.addColorStop(1, 'rgba(0,0,0,0.5)');
  ctx.fillStyle = vg;
  ctx.fillRect(0, 0, W, H);

  // grain
  const g = grain[f % grain.length];
  ctx.globalAlpha = 0.05;
  ctx.globalCompositeOperation = 'overlay';
  const s = g.width;
  const ox = -((f * 37) % s), oy = -((f * 53) % s);
  for (let y = oy; y < H; y += s) for (let x = ox; x < W; x += s) ctx.drawImage(g, x, y);
  ctx.globalCompositeOperation = 'source-over';
  ctx.globalAlpha = 1;
}

/* ── main ──────────────────────────────────────────────────────────── */
(async () => {
  console.log(`promo: ${TOTAL} frames (${(TOTAL / FPS).toFixed(1)}s) at ${W}x${H}`);

  const imgs = {};
  for (const n of [...new Set(SHOTS.filter((s) => s.img).map((s) => s.img))]) {
    imgs[n] = await loadImage(fs.readFileSync(path.join(IMG, `${n}-1600.jpg`)));
  }
  const PHOTOS = path.join(__dirname, 'photos');
  for (const n of [...new Set(SHOTS.filter((s) => s.src).map((s) => s.src))]) {
    imgs[n] = await loadImage(fs.readFileSync(path.join(PHOTOS, n)));
  }
  const wordmark = await loadImage(fs.readFileSync(path.join(IMG, 'wordmark.png')));

  // the procedural plate, native 9:16
  const A = scene.buildAssets(W, H);
  const scratch = { upper: createCanvas(W, H), sky: createCanvas(W, H) };
  const plate = createCanvas(W, H);
  const plateCtx = plate.getContext('2d');

  const grain = buildGrain();
  const canvas = createCanvas(W, H);
  const ctx = canvas.getContext('2d');

  // absolute start frame of each shot
  const starts = [];
  let acc = 0;
  for (const s of SHOTS) { starts.push(acc); acc += s.d; }

  /** Draw one shot's picture content at local progress t (0..1), frame f. */
  function drawShot(c, si, t, f) {
    const s = SHOTS[si];
    if (s.kind === 'plate' || s.kind === 'end') {
      // 12s loop of the dusk scene, sampled where this shot sits
      scene.drawFrame(plateCtx, W, H, ((f / FPS) / 12) % 1, A, scratch);
      const z = s.kind === 'end' ? lerp(1.12, 1.02, smooth(t)) : lerp(1.14, 1.0, smooth(t));
      const bw = W * z, bh = H * z;
      c.drawImage(plate, (W - bw) / 2, (H - bh) / 2, bw, bh);
      return;
    }
    const e = smooth(t);
    drawCover(c, imgs[s.img || s.src], lerp(s.z[0], s.z[1], e),
      lerp(s.p[0], s.p[2], e), lerp(s.p[1], s.p[3], e));
  }

  /* ── ffmpeg ───────────────────────────────────────────────────── */
  const out = path.join(OUT, 'promo-vertical.mp4');
  const tmp = path.join(OUT, '.promo-raw.mp4');
  const proc = spawn(ffmpeg, [
    '-y', '-f', 'rawvideo', '-pixel_format', 'rgba',
    '-video_size', `${W}x${H}`, '-framerate', String(FPS), '-i', 'pipe:0',
    '-an', '-c:v', 'libx264', '-preset', 'slow', '-crf', '21',
    '-pix_fmt', 'yuv420p', '-profile:v', 'high', '-level', '4.1',
    tmp,
  ], { stdio: ['pipe', 'ignore', 'pipe'] });
  let err = '';
  proc.stderr.on('data', (d) => { err += d; });
  const write = (b) => new Promise((r) => {
    if (proc.stdin.write(b)) r(); else proc.stdin.once('drain', r);
  });

  for (let f = 0; f < TOTAL; f++) {
    // which shot?
    let si = 0;
    while (si < SHOTS.length - 1 && f >= starts[si] + SHOTS[si].d) si++;
    const local = f - starts[si];
    const t = clamp(local / SHOTS[si].d, 0, 1);

    ctx.setTransform(1, 0, 0, 1, 0, 0);
    ctx.globalAlpha = 1;
    ctx.fillStyle = '#06060b';
    ctx.fillRect(0, 0, W, H);

    // crossfade in from the previous shot unless this is a hard cut
    const xf = SHOTS[si].cut === 'hard' ? 0 : XF;
    if (si > 0 && local < xf) {
      const prev = si - 1;
      drawShot(ctx, prev, 1, f);
      ctx.globalAlpha = smooth(local / xf);
      drawShot(ctx, si, t, f);
      ctx.globalAlpha = 1;
    } else {
      drawShot(ctx, si, t, f);
    }

    // a one-frame gold flash on hard cuts gives the montage its snap
    if (SHOTS[si].cut === 'hard' && local === 0) {
      ctx.globalCompositeOperation = 'lighter';
      ctx.fillStyle = 'rgba(226,178,106,0.30)';
      ctx.fillRect(0, 0, W, H);
      ctx.globalCompositeOperation = 'source-over';
    }

    grade(ctx, f, grain);

    /* ── overlays ─────────────────────────────────────────────── */
    if (SHOTS[si].kind === 'plate') {
      // opener: wordmark settles in, tagline beneath
      const a = smooth(clamp((local - 8) / 22, 0, 1)) * smooth(clamp((SHOTS[si].d - local) / 12, 0, 1));
      const ww = W * 0.74, wh = wordmark.height * (ww / wordmark.width);
      ctx.globalAlpha = a;
      ctx.drawImage(wordmark, (W - ww) / 2, H * 0.44 - wh / 2 - (1 - smooth(clamp((local - 8) / 22, 0, 1))) * 18, ww, wh);
      ctx.globalAlpha = a * 0.9;
      ctx.textAlign = 'center';
      ctx.fillStyle = CREAM;
      ctx.font = '400 30px InstrumentSans';
      ctx.letterSpacing = '6px';
      ctx.fillText('LA BRUYÈRE · BELGIQUE', W / 2, H * 0.44 + wh * 0.72);
      ctx.letterSpacing = '0px';
      ctx.globalAlpha = 1;
    } else if (SHOTS[si].kind === 'end') {
      const a = smooth(clamp(local / 16, 0, 1));
      ctx.fillStyle = `rgba(6,6,11,${0.55 * a})`;
      ctx.fillRect(0, 0, W, H);

      const ww = W * 0.78, wh = wordmark.height * (ww / wordmark.width);
      ctx.globalAlpha = a;
      ctx.drawImage(wordmark, (W - ww) / 2, H * 0.40 - wh / 2, ww, wh);

      ctx.textAlign = 'center';
      ctx.fillStyle = CREAM;
      ctx.font = '400 34px InstrumentSans';
      ctx.letterSpacing = '2px';
      ctx.fillText('Réservez en direct', W / 2, H * 0.40 + wh * 0.78);

      // the URL sits above TikTok's bottom UI band
      const bt = smooth(clamp((local - 14) / 18, 0, 1));
      ctx.globalAlpha = a * bt;
      const label = 'vanfryddie.github.io/emines-de-rien';
      ctx.font = '600 27px InstrumentSans';
      ctx.letterSpacing = '0px';
      const tw = ctx.measureText(label).width;
      const bw = tw + 64, bh2 = 76, bx = (W - bw) / 2, byy = H * 0.63;
      ctx.fillStyle = GOLD;
      ctx.beginPath(); ctx.roundRect(bx, byy, bw, bh2, bh2 / 2); ctx.fill();
      ctx.fillStyle = '#17110a';
      ctx.fillText(label, W / 2, byy + 49);
      ctx.letterSpacing = '0px';
      ctx.globalAlpha = 1;
    } else if (SHOTS[si].t) {
      drawCaption(ctx, SHOTS[si].t, t, SHOTS[si].d);
    }

    const data = ctx.getImageData(0, 0, W, H).data;
    await write(Buffer.from(data.buffer, data.byteOffset, data.byteLength));
    if (f % 90 === 0) process.stdout.write(`  ${f}/${TOTAL}\n`);
  }

  proc.stdin.end();
  const code = await new Promise((r) => proc.on('close', r));
  if (code !== 0) { console.error(err.slice(-2500)); process.exit(1); }

  // Separate remux for faststart, then verify the result actually decodes.
  const { spawnSync } = require('child_process');
  const rm = spawnSync(ffmpeg, ['-y', '-i', tmp, '-c', 'copy',
    '-movflags', '+faststart', out], { encoding: 'utf8' });
  if (rm.status !== 0) { console.error(rm.stderr.slice(-2000)); process.exit(1); }
  fs.unlinkSync(tmp);

  const probe = spawnSync(ffmpeg, ['-i', out], { encoding: 'utf8' });
  const line = (probe.stderr.match(/Stream #0:0.*/) || ['(no stream)'])[0];
  const dur = (probe.stderr.match(/Duration: [^,]+/) || ['?'])[0];
  if (/moov atom not found|Invalid data/.test(probe.stderr)) {
    console.error('output did not decode:\n' + probe.stderr.slice(-800));
    process.exit(1);
  }
  console.log('verified:', dur, '|', line.replace(/\s+/g, ' ').slice(0, 110));

  const mb = (fs.statSync(out).size / 1048576).toFixed(2);
  console.log(`\npromo-vertical.mp4 — ${mb} MB, ${(TOTAL / FPS).toFixed(1)}s, ${W}x${H}`);

  // a cover frame for thumbnails
  const cover = createCanvas(W, H);
  cover.getContext('2d').drawImage(canvas, 0, 0);
  fs.writeFileSync(path.join(OUT, 'promo-cover.jpg'), cover.encodeSync('jpeg', 86));
})();
